name: DotNet

on: [pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    name: Format
    steps:
      - uses: actions/checkout@v4

      - name: Run dotnet format
        run: |
          dotnet format --verify-no-changes
